#%RAML 1.0 NamedExample
value:
-
  "customerNumber": 103
  "country": "France"
  "contactFirstName": "Carine "
  "city": "Nantes"
  "contactLastName": "Schmitt"
  "phone": "40.32.2555"
  "postalCode": "44000"
  "addressLine2": null
  "addressLine1": "54, rue Royale"
  "salesRepEmployeeNumber": 1370
  "state": null
  "customerName": "donaldo"
  "creditLimit": 25000.00
-
  "customerNumber": 119
  "country": "France"
  "contactFirstName": "Janine "
  "city": "Nantes"
  "contactLastName": "Labrune"
  "phone": "40.67.8555"
  "postalCode": "44000"
  "addressLine2": null
  "addressLine1": "67, rue des Cinquante Otages"
  "salesRepEmployeeNumber": 1370
  "state": null
  "customerName": "La Rochelle Gifts"
  "creditLimit": 118200.00