#%RAML 1.0 NamedExample
value:
-
  "orderNumber": "10094"
  "orderDate": "2004-08-30T00:00:00"
  "customerNumber": 103
  "comments": "deliverd"
  "shippedDate": "2004-09-01T00:00:00"
  "requiredDate": "2004-09-06T00:00:00"
  "status": "Shipped"
  "orderDetails":
  -
    "productCode": "S10_1678"
    "quantityOrdered": 20
    "priceEach": 190.68
    "orderLineNumber": 0
  -
    "productCode": "S10_1949"
    "quantityOrdered": 40
    "priceEach": 117.44
    "orderLineNumber": 0
-
  "orderNumber": "10095"
  "orderDate": "2005-08-30T00:00:00"
  "customerNumber": 103
  "comments": "deliverd"
  "shippedDate": "2005-09-01T00:00:00"
  "requiredDate": "2005-09-06T00:00:00"
  "status": "Shipped"
  "orderDetails":
  -
    "productCode": "S10_1679"
    "quantityOrdered": 21
    "priceEach": 290.68
    "orderLineNumber": 0
  -
    "productCode": "S10_1950"
    "quantityOrdered": 50
    "priceEach": 137.44
    "orderLineNumber": 0