#%RAML 1.0 NamedExample
value:
-
  "productLine": "Motorcycles"
  "productScale": "1:10"
  "productCode": "S10_1678"
  "productVendor": "Min Lin Diecast"
  "productDescription": "This replica features working kickstand, front suspension, gear-shift lever, footbrake lever, drive chain, wheels and steering. All parts are particularly delicate due to their precise scale and require special care and attention."
  "buyPrice": 48.81
  "quantityInStock": 7933
  "MSRP": 95.70
  "productName": "SheetsNew"
-
  "productLine": "Classic Cars"
  "productScale": "1:10"
  "productCode": "S10_1949"
  "productVendor": "Classic Metal Creations"
  "productDescription": "Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis."
  "buyPrice": 98.58
  "quantityInStock": 7305
  "MSRP": 214.30
  "productName": "1952 Alpine Renault 1300"