#%RAML 1.0 DataType

displayName: Customer

type: object
properties:
  "customerNumber": integer
  "country": string
  "contactFirstName": string
  "city": string
  "contactLastName": string
  "phone": string
  "postalCode": string
  "addressLine2": nil
  "addressLine1": string
  "salesRepEmployeeNumber": number
  "state": nil
  "customerName": string
  "creditLimit": number