#%RAML 1.0 DataType

displayName: Order

type: object
properties:
  orderNumber: string
  orderDate: string
  customerNumber: integer
  comments: string
  shippedDate: string
  requiredDate: string
  status: string
  orderDetails: 
    type: array
    items:
      type: !include orderDetailsDataType.raml

