#%RAML 1.0 DataType

displayName: Product

type: object
properties:
  "productLine": string
  "productScale": string
  "productCode": string
  "productVendor": string
  "productDescription": string
  "buyPrice": number
  "quantityInStock": integer
  "MSRP": number
  "productName": string